
name: Resume Screening Dashboard CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint check (non-blocking)
      run: |
        pip install flake8
        echo "Running flake8 (style warnings will not fail CI)"
        flake8 . --count --max-complexity=20 --max-line-length=127 --statistics || true

    - name: Run tests (non-blocking)
      run: |
        echo "Running pytest (won't fail CI if tests fail)"
        pytest -q || true

    - name: Run Streamlit app
      run: |
        streamlit run app3.py --server.headless true &
        sleep 10
